default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ocsc-tms-cloud_development
test:
  <<: *default
  database: ocsc-tms-cloud_test
production:
  <<: *default
  database: ocsc-tms-cloud_production
  username: deploy
